export const tools = [
"PDF to Word",
"Word to PDF",
"Merge PDF",
"Split PDF",
"Compress PDF",
"Image to PDF",
"PNG to JPG",
"JPG to PNG",
"WebP to PNG",
"Image Compressor",
"QR Code Generator",
"Barcode Generator",
"Password Generator",
"Password Strength Checker",
"UUID Generator",
"JSON Formatter",
"Base64 Encoder",
"Base64 Decoder",
"URL Encoder",
"URL Decoder",
"HTML Minifier",
"CSS Minifier",
"JS Minifier",
"Markdown to HTML",
"HTML to Markdown",
"Word Counter",
"Character Counter",
"Case Converter",
"Slug Generator",
"Meta Tag Generator",
"Meta Description Generator",
"Robots.txt Generator",
"Sitemap Generator",
"Keyword Density Checker",
"Readability Checker",
"YouTube Thumbnail Downloader",
"YouTube Title Generator",
"AdSense Revenue Calculator",
"ROI Calculator",
"Percentage Calculator",
"Loan Calculator",
"Mortgage Calculator",
"BMI Calculator",
"Age Calculator",
"Time Zone Converter",
"Unit Converter",
"Currency Converter",
"Random Name Generator",
"Random Number Generator",
"Color Palette Generator"
];
